language: objective-c
osx_image: xcode8

branches:
  only:
    - master

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="FeatherweightRouter"
    - IOS_SDK=iphonesimulator9.3
    - MACOS_SDK=macosx10.11
    - TVOS_SDK=appletvsimulator9.2
    - WATCHOS_SDK=watchsimulator2.2
  matrix:
    - DESTINATION="arch=x86_64" SCHEME="macOS" SDK="$MACOS_SDK" ACTION="test"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    "$ACTION"
    | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
