language: objective-c
osx_image: xcode8

env:
  - ACTION="test"  SDK="macosx10.12"          DESTINATION="arch=x86_64"
  - ACTION="test"  SDK="iphonesimulator10.0"  DESTINATION="OS=10.0,name=iPhone 7 Plus"
  - ACTION="test"  SDK="appletvsimulator10.0" DESTINATION="OS=10.0,name=Apple TV 1080p"
  - ACTION="build" SDK="watchsimulator3.0"    DESTINATION="OS=3.0,name=Apple Watch Series 2 - 42mm"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -scheme FeatherweightRouter
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    "$ACTION"
    | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
